### PR TITLE
feat(rewrite): next app

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
This PR re-writes the site to use Next.js based on the new designs here https://www.figma.com/file/DHlhOWT0BqzCDDlirCHLMQ/Bitcoin-Knowledge-project?node-id=542%3A1913&mode=dev.

Generally ready, however there needs to be some clarification for how to populate the curriculum template and with which data. For now, this data is mocked.

### CODE REVIEW

**Comment by adamjonas** [comment]
Looks like a good start. I think we will want a gutter rather than the content bleeding to the edges but worth getting on a vercel preview and having the designers take a look.

**Comment by adamjonas** [comment]
The images still appear stretched on mobile. A couple of things that stand out:

image

Text alignment and spacing on mobile 


image

The footer should be fixed

**Comment by adamjonas** [comment]
Need bulletpoints aligned on mobile image

**Comment by adamjonas** [comment]
Did we agree to a hamburger menu for mobile?

image

**Comment by BalogunofAfrica** [comment]
> Did we agree to a hamburger menu for mobile?
> 
> image

Would add it now

**Comment by adamjonas** [comment]
Is this the image or some css causing the white bit the bottom of this image?

image

**Comment by adamjonas** [comment]
I know you didn't have a mobile design but this full width hero image feels out of place on mobile 

image

Let's put it above the learn, contribute, build buttons and add margins like the other images

**Comment by BalogunofAfrica** [comment]
> Is this the image or some css causing the white bit the bottom of this image?
> 
> image

It is the image, it seems to be caused by an error when exporting. Would re-export and update

**Comment by adamjonas** [comment]
Art is seeing this on android chrome and brave

image

**Comment by mouxdesign** [comment]
Hi dev crew! Mo here. Some design comments for the homepage only.
Group 14090 (1)

Explore image at the bottom of the homepage. Re-created an image for the mobile view so that it does not appear squashed when viewed on mobile. Link to [figma](https://www.figma.com/file/DHlhOWT0BqzCDDlirCHLMQ/Bitcoin-Knowledge-project?type=design&node-id=779-2440&mode=dev)

Screenshot_20231117-151851

**Comment by BalogunofAfrica** [comment]
Hi @mouxdesign, thanks for the review.

I have addressed them and also left a comment on Figma :)

**Comment by mouxdesign** [comment]
Thank you! Could you please share the latest preview link? I have this as the most [recent link.](https://bitcoin-dev-project-efagyefdq-btc-knowledge-base.vercel.app/). t does not seem to be showing the updates though.

Also provided an image in [figma](https://www.figma.com/file/DHlhOWT0BqzCDDlirCHLMQ/Bitcoin-Knowledge-project?type=design&node-id=779-2443&mode=dev) with no gap.

**Comment by BalogunofAfrica** [comment]
> Thank you! Could you please share the latest preview link? I have this as the most [recent link.](https://bitcoin-dev-project-efagyefdq-btc-knowledge-base.vercel.app/). t does not seem to be showing the updates though.
> 
> Also provided an image in [figma](https://www.figma.com/file/DHlhOWT0BqzCDDlirCHLMQ/Bitcoin-Knowledge-project?type=design&node-id=779-2443&mode=dev) with no gap.

Alright, thank you. Would update the image, here's the latest preview link: [bitcoin dev preview](https://bitcoin-dev-project-137euup0k-btc-knowledge-base.vercel.app/)

**Comment by BalogunofAfrica** [comment]
@mouxdesign  I have updated the image, here's the [latest preview](https://bitcoin-dev-project-zbcjkuxse-btc-knowledge-base.vercel.app/)

**Comment by Extheoisah** [comment]
incorrect sentence in footer
image

**Comment by adamjonas** [comment]
Screenshot 2023-11-30 at 4 00 09 PM

I don't like the scroll here. I'm loading a new page but it feels like I'm scrolling to the top of the page I'm already on and the background is refreshing while I do.

**Comment by mouxdesign** [comment]
Here are the [design files](https://www.figma.com/file/DHlhOWT0BqzCDDlirCHLMQ/Bitcoin-Knowledge-project?type=design&node-id=825-1204&mode=dev) for the Build page. It includes:
- Copy
- Images
- Links: 
1. Transaction Tutorial [link](https://github.com/chaincodelabs/bitcoin-tx-tutorial)
2. Minesim [link](https://github.com/LarryRuane/minesim#exercises-discussion-questions)
3. Tinybitcoinpeer [link](https://github.com/willcl-ark/tinybitcoinpeer)
4. Optech Schnorr Taproot Workshop [link](https://bitcoinops.org/en/schorr-taproot-workshop)
5. Build on Lightning Tutorial [link](https://buildonln.com/)
6. Polar [link](https://lightningpolar.com/)
7. SimLN [link](https://simln.dev/)

Build (2)

**Comment by BalogunofAfrica** [comment]
Closed by https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/25

**Pull request closed without merging**
