### PR TITLE
Implement feedback from Jonas on issue #105

### PR DESCRIPTION
**Pull request by jrakibi**
This PR addresses the feedback from Jonas as outlined in [issue #105](https://github.com/bitcoin-dev-project/bitcoin-dev-project/issues/105)

### CODE REVIEW

**Comment by IgboPharaoh** [comment]
Hello Jamal, I think this PR should be raised against the staging branch.

**Comment by jrakibi** [comment]
> Hello Jamal, I think this PR should be raised against the staging branch.

you're right
fixed

**Comment by adamjonas** [comment]
Landed on bottom of https://bitcoin-dev-project-rcaldlvw5-btc-knowledge-base.vercel.app/topics/2-community using next button

**Comment by jrakibi** [comment]
@Emmanuel-Develops, can you check if you're also experiencing the issue of landing at the bottom of the page? It seems to be working fine on my two phones

> ## Landed on bottom of https://bitcoin-dev-project-rcaldlvw5-btc-knowledge-base.vercel.app/topics/2-community using next button
> Same https://bitcoin-dev-project-rcaldlvw5-btc-knowledge-base.vercel.app/topics/3-overview
> And https://bitcoin-dev-project-rcaldlvw5-btc-knowledge-base.vercel.app/topics/3-4-overview-script-success-failure
> And https://bitcoin-dev-project-rcaldlvw5-btc-knowledge-base.vercel.app/topics/3-6-overview-data
> Newsletter box still above next previous buttons
> 
> The his code block is weird. And why it's in JS is wierder.
> 
> image

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops, can you check if you're also experiencing the issue of landing at the bottom of the page? It seems to be working fine on my two phones

@jrakibi worked fine on mine up until I opened the deployment in brave browser. I observed the same behavior as jonas.
screen recording below:

https://github.com/user-attachments/assets/fb222cfb-6c3d-4cfe-a73d-dcbce774a9c8

**Review by Emmanuel-Develops — APPROVED** [review]

**Pull request merged**
