### PR TITLE
Change url and product name

### PR DESCRIPTION
**Pull request by jrakibi**
This PR changes the URL to use `/learn` instead of `/topics` and renames the product to `'Decoding Bitcoin'` instead of `'Bitcoin Topics'`

### CODE REVIEW

**Comment by Emmanuel-Develops** [comment]
the deployed version shows 404 on '/learn'
cc: @jrakibi

**Comment by jrakibi** [comment]
> the deployed version shows 404 on '/learn' cc: @jrakibi

Oh I guess, we have to merge first the PR for the other PR on `bitcoin-topics`

**Comment by Emmanuel-Develops** [comment]
> > the deployed version shows 404 on '/learn' cc: @jrakibi
> 
> Oh I guess, we have to merge first the PR for the other PR on `bitcoin-topics` [bitcoin-dev-project/bitcoin-topics#10](https://github.com/bitcoin-dev-project/bitcoin-topics/pull/10)

merged on [bitcoin-topics](bitcoin-dev-project/bitcoin-topics#10)!

**Comment by Emmanuel-Develops** [comment]
You need to update the submodules and commit so it reflects in this PR.

Also, we'll need a workflow file to update submodules.
cc: @jrakibi

**Comment by jrakibi** [comment]
> You need to update the submodules and commit so it reflects in this PR.
> 
> Also, we'll need a workflow file to update submodules. cc: @jrakibi

I think just redeploying will trigger the build and pull the new changes from the other repo. We don’t need to make any commits when we only change the content

**Comment by jrakibi** [comment]
@Emmanuel-Develops I upadated the other repo to use `/decoding` instead of `/learn`, also this the commit that updates the url in this repo https://github.com/bitcoin-dev-project/bitcoin-dev-project/pull/111/commits/405307a7a005f1f4cc8c8f73c137a61ebd97abaa

**Review by Emmanuel-Develops — APPROVED** [review]

**Pull request merged**
