### PR TITLE
fixes: copytext and style changes

### PR DESCRIPTION
**Pull request by IgboPharaoh**
- This PR attends to different text fixes and corrections from this [deployment](https://bitcoin-dev-project-git-staging-btc-knowledge-base.vercel.app/)

### CODE REVIEW

**Comment by jrakibi** [comment]
Great work on this! I have just a couple of comments:

1. It seems like the fix for "clicking outside of the menu should pull the menu up" was missed.
2. The changes for updating the header menu icons and making them inline are also missing.

If you'd prefer, we can merge this, and I can open a PR specifically addressing the issue with the icons.

**Comment by IgboPharaoh** [comment]
> Great work on this! I have just a couple of comments:
> 
> 1. It seems like the fix for "clicking outside of the menu should pull the menu up" was missed.
> 2. The changes for updating the header menu icons and making them inline are also missing.
> 
> If you'd prefer, we can merge this, and I can open a PR specifically addressing the issue with the icons.

I didn't see those comments, will add them to this pr

**Comment by IgboPharaoh** [comment]
Changes have been pushed @jrakibi

**Comment by jrakibi** [comment]
> Changes have been pushed @jrakibi

Perfect, this looks good to me. 
@Extheoisah If there are no comments/feedback from you, we can get this deployed

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
